import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * [AUTOGENERATED] by typeorm
 * Adds all indices or drops them
 */
export class AddedIndices1607447216655 implements MigrationInterface {
	name = 'AddedIndices1607447216655';

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`CREATE UNIQUE INDEX "IDX_72829cd4f7424e3cdfd46c476c" ON "login_attempt" ("id") `,
		);
		await queryRunner.query(
			`CREATE INDEX "IDX_0f39a5f0d8be9cf362f839764c" ON "login_attempt" ("timestamp") `,
		);
		await queryRunner.query(
			`CREATE UNIQUE INDEX "IDX_b36bcfe02fc8de3c57a8b2391c" ON "role" ("id") `,
		);
		await queryRunner.query(
			`CREATE INDEX "IDX_c418809d8c85e0e2c666482f5a" ON "sms_token" ("token") `,
		);
		await queryRunner.query(
			`CREATE UNIQUE INDEX "IDX_cace4a159ff9f2512dd4237376" ON "user" ("id") `,
		);
		await queryRunner.query(
			`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `,
		);
		await queryRunner.query(
			`CREATE INDEX "IDX_8e1f623798118e629b46a9e629" ON "user" ("phone") `,
		);
		await queryRunner.query(
			`CREATE UNIQUE INDEX "IDX_be5fda3aac270b134ff9c21cde" ON "post" ("id") `,
		);
		await queryRunner.query(
			`CREATE INDEX "IDX_f5b12b405e3ba99533c1dfdbd4" ON "post" ("status") `,
		);
		await queryRunner.query(
			`CREATE UNIQUE INDEX "IDX_0b0e4bbc8415ec426f87f3a88e" ON "comment" ("id") `,
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP INDEX "IDX_0b0e4bbc8415ec426f87f3a88e"`);
		await queryRunner.query(`DROP INDEX "IDX_f5b12b405e3ba99533c1dfdbd4"`);
		await queryRunner.query(`DROP INDEX "IDX_be5fda3aac270b134ff9c21cde"`);
		await queryRunner.query(`DROP INDEX "IDX_8e1f623798118e629b46a9e629"`);
		await queryRunner.query(`DROP INDEX "IDX_e12875dfb3b1d92d7d7c5377e2"`);
		await queryRunner.query(`DROP INDEX "IDX_cace4a159ff9f2512dd4237376"`);
		await queryRunner.query(`DROP INDEX "IDX_c418809d8c85e0e2c666482f5a"`);
		await queryRunner.query(`DROP INDEX "IDX_b36bcfe02fc8de3c57a8b2391c"`);
		await queryRunner.query(`DROP INDEX "IDX_0f39a5f0d8be9cf362f839764c"`);
		await queryRunner.query(`DROP INDEX "IDX_72829cd4f7424e3cdfd46c476c"`);
	}
}
